// Generated by ts-to-zod
import { z } from "zod";

export const answerSchema = z.object({
  text: z.string(),
  correct: z.boolean(),
});

export const baseQuestionSchema = z.object({
  uid: z.string(),
  text: z.string(),
  questionType: z.string(),
  answers: z.array(answerSchema),
  time: z.number().optional(),
  explanation: z.string().optional(),
  tags: z.array(z.string()).optional(),
});
