// Generated by ts-to-zod
import { z } from "zod";

export const participantSchema = z.object({
  id: z.string(),
  username: z.string(),
  avatar: z.string(),
  score: z.number(),
  isDeferred: z.boolean().optional(),
  socketId: z.string().optional(),
  scoredQuestions: z.record(z.number()).optional(),
});

// Removed unused schemas:
// - tournamentAnswerSchema (only used within this file)
// - tournamentParticipantSchema (never imported)
// - leaderboardEntrySchema (duplicate of core/leaderboardEntry.zod.ts)
