// Generated by ts-to-zod
import { z } from "zod";

export const questionTimerStateSchema = z.object({
  timeLeft: z.number(),
  initialTime: z.number(),
  lastUpdateTime: z.number(),
  status: z.union([z.literal("play"), z.literal("pause"), z.literal("stop")]),
});

export const questionStateSchema = z.object({
  uid: z.string(),
  totalTime: z.number(),
  correctAnswers: z.union([z.number(), z.array(z.number())]),
});

const tournamentParticipantSchema = z.any();

const questionSchema = z.any();

const tournamentAnswerSchema = z.any();
